spring:
  application:
    name: aggregator
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

  config:
    import: "configserver:"

eureka:
  instance:
    discovery-hostname: localhost
    discovery-port: 8761
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.discovery-hostname}:${eureka.instance.discovery-port}/eureka/