spring:
  application:
    name: aggregator
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

  config:
    import: "configserver:"

eureka:
  instance:
    discovery-hostname: localhost
    discovery-port: 8761
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.discovery-hostname}:${eureka.instance.discovery-port}/eureka/