services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - /opt/initsql/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh