logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      appache.kafka: WARN

grpc:
  server:
    port: 0

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.collector"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        user-actions: stats.user-actions.v1