logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      appache.kafka: WARN

aggregator:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.aggregator"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        events-similarity: stats.events-similarity.v1
    consumer:
      properties:
        group.id: "aggregator-client"
        bootstrap.servers: localhost:9092
        client.id: "stats.aggregator"
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.practicum.kafka.serializer.UserActionDeserializer
        enable.auto.commit: false
      topics:
        user-actions: stats.user-actions.v1
      poll-timeout: 100ms
  action-weight:
    view: 0.4
    register: 0.8
    like: 1.0