-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS participation_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(10) NOT NULL,
  CONSTRAINT ux_event_requester UNIQUE (event_id, requester_id)
);

ALTER TABLE participation_requests DROP CONSTRAINT IF EXISTS participation_requests_state_check;
ALTER TABLE participation_requests ADD CONSTRAINT participation_requests_state_check CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED', 'REJECTED'));

COMMENT ON TABLE participation_requests IS 'Содержит информацию о событиях';
COMMENT ON COLUMN participation_requests.id IS 'Уникальный идентификатор заявки на участие в событии';
COMMENT ON COLUMN participation_requests.created IS 'Дата и время создания заявки на участие в событии';
COMMENT ON COLUMN participation_requests.event_id IS 'Идентификатор события';
COMMENT ON COLUMN participation_requests.requester_id IS 'Идентификатор пользователя, отправившего заявку';
COMMENT ON COLUMN participation_requests.status IS 'Статус заявки на участие в событии';