spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/admin/compilations/**,/admin/events/**,/categories/**,/compilations/**,/events/**,/users/{userId}/events/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/comments/**,/users/{userId}/comments/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

server:
  port: 8080