spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: sa
    password: password

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
      hibernate.SQL: TRACE
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
        web.filter.CommonsRequestLoggingFilter: DEBUG

analyzer:
  kafka:
    action-consumer:
      properties:
        group.id: "analyzer-action-client"
        bootstrap.servers: localhost:9092
        client.id: "stats.analyzer.action"
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.practicum.kafka.serializer.UserActionDeserializer
        enable.auto.commit: false
      topics:
        user-actions: stats.user-actions.v1
      poll-timeout: 500ms
    similarity-consumer:
      properties:
        group.id: "analyzer-similarity-client"
        bootstrap.servers: localhost:9092
        client.id: "stats.analyzer.similarity"
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.practicum.kafka.serializer.EventSimilarityDeserializer
        enable.auto.commit: false
      topics:
        events-similarity: stats.events-similarity.v1
      poll-timeout: 500ms
  action-weight:
    view: 0.4
    register: 0.8
    like: 1.0

grpc:
  server:
    port: 0