spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/events
    username: sa
    password: password

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
      hibernate.SQL: TRACE
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
        web.filter.CommonsRequestLoggingFilter: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 3
      failureRateThreshold: 50

server:
  port: 0

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext